{
 "title": "CF databases",
 "description": "Cloud Foundry database metrics from paas-prometheus-exporter",
 "tags": [
  "prometheus",
  "cloudfoundry",
  "db",
  "database",
  "postgres",
  "postgresql",
  "mysql"
 ],
 "time": { "from": "now-1h", "to": "now" },
 "templating": {
  "list": [
   { "name": "SpaceName", "label": "SpaceName", "query": "label_values(cpu,space)" },
   {
    "name": "Services",
    "label": "Services",
    "query": "label_values(connections{space =~\"$SpaceName\"},service)"
   }
  ]
 },
 "panels": [
  {
   "title": "Database Size",
   "type": "stat",
   "gridPos": { "h": 7, "w": 3, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "options": { "reduceOptions": { "calcs": [ "max" ] } },
   "targets": [
    {
     "expr": "swap_usage_bytes{ service=~ \"$Services\" }",
     "legendFormat": "Swap"
    },
    {
     "expr": "dbsize_byte{ service=~ \"$Services\" }",
     "legendFormat": "Used"
    },
    {
     "expr": "free_storage_space_bytes{ service=~ \"$Services\" }",
     "legendFormat": "Free"
    }
   ]
  },
  {
   "title": "Dead Locks",
   "type": "stat",
   "description": "In concurrent systems where resources are locked, two or more processes can end up in a state in which each process is waiting for the other one. This state is called a deadlock. ",
   "gridPos": { "h": 7, "w": 4, "x": 3, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "deadlocks{ service=~\"$Services\"}",
     "legendFormat": "{{service}}"
    }
   ]
  },
  {
   "title": "Connections",
   "type": "graph",
   "gridPos": { "h": 6, "w": 17, "x": 7, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "connections{ service=\"$Services\" }",
     "legendFormat": "Connected"
    },
    {
     "expr": "blocked_connections{ service=\"$Services\" }",
     "legendFormat": "Blocked"
    }
   ]
  },
  {
   "title": "Available Free Memory",
   "type": "graph",
   "gridPos": { "h": 6, "w": 17, "x": 7, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "yaxes": [
    { "format": "decbytes" }
   ],
   "targets": [
    {
     "expr": "freeable_memory_bytes{service=\"$Services\"}",
     "legendFormat": "USAGE"
    }
   ]
  },
  {
   "title": "Database size",
   "type": "grafana-piechart-panel",
   "gridPos": { "h": 6, "w": 7, "x": 0, "y": 7 },
   "format": "decbytes",
   "valueName": "current",
   "targets": [
    {
     "expr": "dbsize_byte{space=\"$SpaceName\", service=\"$Services\"}",
     "legendFormat": "Used"
    },
    {
     "expr": "free_storage_space_bytes{space=\"$SpaceName\", service=\"$Services\"}",
     "legendFormat": "Free"
    }
   ]
  },
  {
   "title": "% CPU",
   "type": "graph",
   "gridPos": { "h": 6, "w": 17, "x": 7, "y": 12 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "cpu_percent{ service=\"$Services\" }",
     "legendFormat": "% CPU "
    }
   ]
  },
  {
   "title": "Scans/s",
   "type": "graph",
   "description": "Scans are how the database gathers data from its queries. What we want to see are index Scans in most cases, however table scans are acceptable but must not get out of control",
   "gridPos": { "h": 6, "w": 7, "x": 0, "y": 13 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "rate( idx_scan{ service=~\"$Services\"}[$__rate_interval])",
     "legendFormat": "Index"
    },
    {
     "expr": "rate( seq_scan{ service=~\"$Services\"}[$__rate_interval])",
     "legendFormat": "Sequential"
    }
   ]
  },
  {
   "title": "IOPS",
   "type": "graph",
   "description": "Input/output operations per second is an input/output performance, \nWrite isn't too bad as you want to write new data, but a lot of reads can indicate the database is scanning complete tables for information, which is slow",
   "gridPos": { "h": 6, "w": 17, "x": 7, "y": 18 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "write_iops{ service=~\"$Services\"}",
     "legendFormat": "Write "
    },
    {
     "expr": "read_iops{ service=~\"$Services\"}",
     "legendFormat": "Read"
    }
   ]
  },
  {
   "title": "Rollbacks/min",
   "type": "graph",
   "gridPos": { "h": 6, "w": 7, "x": 0, "y": 19 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "rate( rollbacks{ service=~ \"$Services\"}[$__rate_interval])*60",
     "legendFormat": "{{service}}"
    }
   ]
  }
 ]
}