{
 "title": "CF apps",
 "description": "Cloud Foundry Overview",
 "time": { "from": "now-1h", "to": "now" },
 "refresh": "10s",
 "templating": {
  "list": [
   { "name": "SpaceName", "label": "SpaceName", "query": "label_values(space)" },
   {
    "name": "Applications",
    "label": "Applications",
    "query": "label_values(memory_utilization{space =~\"$SpaceName\"},app)"
   }
  ]
 },
 "panels": [
  {
   "title": "Applications",
   "type": "yesoreyeram-boomtable-panel",
   "gridPos": { "h": 6, "w": 13, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "count by (app) ( cpu{app=~\"$Applications\" , space=\"$SpaceName\"})",
     "legendFormat": "{{app}}|CPU"
    },
    {
     "expr": "sum by (app) ( memory_bytes{app=~\"$Applications\" , space=\"$SpaceName\"})",
     "legendFormat": "{{app}}|MEM"
    },
    {
     "expr": "sum by ( app ) ( disk_bytes{ space=\"$SpaceName\" , app=~\"$Applications\" })",
     "legendFormat": "{{app}}|DISK"
    }
   ]
  },
  {
   "title": "HTTP requests",
   "type": "graph",
   "gridPos": { "h": 7, "w": 23, "x": 0, "y": 6 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(rate(requests{space=\"$SpaceName\", app=~\"$Applications\"}[5m])) by (app) *60",
     "legendFormat": "{{app}} total requests"
    },
    {
     "expr": "sum(rate(requests{space=\"$SpaceName\", app=~\"$Applications\",status_range=~\"0xx|4xx|5xx\"}[5m])) by (app) *60",
     "legendFormat": "{{app}} failed requests"
    }
   ]
  },
  {
   "title": "Response time (seconds)",
   "type": "graph",
   "gridPos": { "h": 7, "w": 23, "x": 0, "y": 13 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "avg(rate(response_time_sum{space=\"$SpaceName\", app=~\"$Applications\"}[1m])) by (app)",
     "legendFormat": "{{app}}"
    }
   ]
  },
  {
   "title": "CPU Usage (%)",
   "type": "graph",
   "gridPos": { "h": 7, "w": 23, "x": 0, "y": 20 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "avg(cpu{space=\"$SpaceName\" , app=~\"$Applications\" }) by (app)",
     "legendFormat": "{{app}}"
    }
   ]
  },
  {
   "title": "Memory Usage (%)",
   "type": "graph",
   "gridPos": { "h": 7, "w": 23, "x": 0, "y": 27 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "avg(memory_utilization{space=\"$SpaceName\" , app=~\"$Applications\" }) by (app)",
     "legendFormat": "{{app}}"
    }
   ]
  },
  {
   "title": "Disk Usage (%)",
   "type": "graph",
   "gridPos": { "h": 7, "w": 23, "x": 0, "y": 34 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "avg by ( app ) ( disk_utilization{ space=\"$SpaceName\" , app=~\"$Applications\" })",
     "legendFormat": "{{app}} "
    }
   ]
  }
 ]
}