{
 "title": "PaaS billing",
 "time": { "from": "now-7d", "to": "now" },
 "refresh": "1h",
 "templating": {
  "list": [
   { "name": "space", "label": "Space", "query": "label_values(cost,space)" },
   {
    "name": "resource_type",
    "label": "Resource type",
    "query": "label_values(cost,resource_type)"
   }
  ]
 },
 "panels": [
  {
   "title": "Total cost [Yesterday]",
   "type": "stat",
   "gridPos": { "h": 4, "w": 9, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "currencyGBP" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(last_over_time(cost{space=~\"$space\"}[1d]))"
    }
   ]
  },
  {
   "title": "Top spaces [Yesterday]",
   "type": "bargauge",
   "gridPos": { "h": 4, "w": 15, "x": 9, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "currencyGBP" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "topk(5,sum(last_over_time(cost{space=~\"$space\", resource_type=~\"$resource_type\"}[1d])) by (space))",
     "legendFormat": "{{space}}"
    }
   ]
  },
  {
   "title": "Cost by space [Yesterday]",
   "type": "grafana-piechart-panel",
   "gridPos": { "h": 11, "w": 12, "x": 0, "y": 4 },
   "format": "currencyGBP",
   "valueName": "current",
   "targets": [
    {
     "expr": "sort_desc(sum(last_over_time(cost{space=~\"$space\", resource_type=~\"$resource_type\"}[1d])) by (space))",
     "legendFormat": "{{space}}"
    }
   ]
  },
  {
   "title": "Cost by resource type [Yesterday]",
   "type": "grafana-piechart-panel",
   "gridPos": { "h": 11, "w": 12, "x": 12, "y": 4 },
   "format": "currencyGBP",
   "valueName": "current",
   "targets": [
    {
     "expr": "sort_desc(sum(last_over_time(cost{space=~\"$space\"}[1d])) by (resource_type))",
     "legendFormat": "{{resource_type}}"
    }
   ]
  },
  {
   "title": "Daily cost by space [Over time]",
   "type": "graph",
   "gridPos": { "h": 15, "w": 24, "x": 0, "y": 15 },
   "yaxes": [
    { "format": "currencyGBP" }
   ],
   "targets": [
    {
     "expr": "sum(last_over_time(cost{space=~\"$space\", resource_type=~\"$resource_type\"}[1d])) by (space)",
     "legendFormat": "{{space}}"
    }
   ]
  }
 ]
}