{
 "title": "Rails",
 "description": "Rails application metrics",
 "time": { "from": "now-15m", "to": "now" },
 "refresh": "10s",
 "templating": {
  "list": [
   {
    "name": "Application",
    "label": "Application",
    "query": {
     "query": "label_values(rails_requests_total,app)"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "Total puma Threads",
   "type": "graph",
   "description": "Thread Pool",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(puma_running{app=~\"$Application\"} - puma_pool_capacity{app=~\"$Application\"})",
     "legendFormat": "Busy"
    },
    {
     "expr": "sum(puma_running{app=~\"$Application\"})",
     "legendFormat": "Running"
    },
    {
     "expr": "sum(puma_max_threads{app=~\"$Application\"})",
     "legendFormat": "Max"
    }
   ]
  },
  {
   "title": "Puma instances activity",
   "type": "bargauge",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "1-puma_pool_capacity{app=\"$Application\"}/puma_max_threads{app=\"$Application\"}",
     "legendFormat": "instance {{exported_instance}}"
    }
   ]
  },
  {
   "title": "Total puma backlog",
   "type": "graph",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 9 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(puma_backlog{app=~\"$Application\"})"
    }
   ]
  },
  {
   "title": "Garbage Collection",
   "type": "stat",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 9 },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "avg(gc_heap_free_slots{app=~\"$Application\"})",
     "legendFormat": "Free Slots"
    },
    {
     "expr": "avg(gc_major_gc_count{app=~\"$Application\"})",
     "legendFormat": "Major GC Count"
    },
    {
     "expr": "avg(gc_heap_allocated_pages{app=~\"$Application\"})",
     "legendFormat": "Heap Allocated Pages"
    }
   ]
  },
  {
   "title": "Throughput",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 15 },
   "yaxes": [
    { "format": "reqps" }
   ],
   "targets": [
    {
     "expr": "sum(increase(rails_requests_total{app=~\"$Application\"}[1m])) by (status)",
     "legendFormat": "{{status}}"
    }
   ]
  },
  {
   "title": "Throughput / Endpoint",
   "type": "graph",
   "gridPos": { "h": 16, "w": 12, "x": 12, "y": 15 },
   "yaxes": [
    { "format": "reqps" }
   ],
   "targets": [
    {
     "expr": "sum(increase(rails_requests_total{app=~\"$Application\"}[1m])) by (controller, action)",
     "legendFormat": "{{controller}}#{{action}}"
    }
   ]
  },
  {
   "title": "Rails average response time",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 22 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "yaxes": [
    { "format": "ms" }
   ],
   "targets": [
    {
     "expr": "sum(increase(rails_db_runtime_seconds_sum{app=~\"$Application\"}[1m]))/sum(increase(rails_db_runtime_seconds_count{app=~\"$Application\"}[1m]))",
     "legendFormat": "ActiveRecord"
    },
    {
     "expr": "sum(increase(rails_view_runtime_seconds_sum{app=~\"$Application\"}[1m]))/sum(increase(rails_view_runtime_seconds_count{app=~\"$Application\"}[1m]))",
     "legendFormat": "Views"
    },
    {
     "expr": "sum(increase(rails_request_duration_seconds_sum{app=~\"$Application\"}[1m]))/sum(increase(rails_request_duration_seconds_count{app=~\"$Application\"}[1m]))\n- sum(increase(rails_db_runtime_seconds_sum{app=~\"$Application\"}[1m]))/sum(increase(rails_db_runtime_seconds_count{app=~\"$Application\"}[1m]))\n- sum(increase(rails_view_runtime_seconds_sum{app=~\"$Application\"}[1m]))/sum(increase(rails_view_runtime_seconds_count{app=~\"$Application\"}[1m]))",
     "legendFormat": "Overhead"
    }
   ]
  }
 ]
}