{
 "title": "Yabeda Delayed Job",
 "time": { "from": "now-12h", "to": "now" },
 "refresh": "10s",
 "templating": {
  "list": [
   {
    "name": "SpaceName",
    "label": "SpaceName",
    "query": {
     "query": "label_values(delayed_job_queue_latency,space)"
    }
   },
   {
    "name": "Apps",
    "label": "Apps",
    "query": {
     "query": "label_values(delayed_job_queue_latency,app)"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "Jobs waiting",
   "type": "stat",
   "description": "Number of jobs waiting in queues to be executed",
   "gridPos": { "h": 4, "w": 4, "x": 0, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "max(delayed_job_jobs_waiting_count{space=\"$SpaceName\"})",
     "legendFormat": "{{queue}}"
    }
   ]
  },
  {
   "title": "Jobs latency",
   "type": "stat",
   "description": "Queue latency is the difference in seconds since the oldest job in the queue was enqueued. Or how long job is waiting its turn to be executed.",
   "gridPos": { "h": 4, "w": 4, "x": 4, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "max(delayed_job_queue_latency{space=\"$SpaceName\"})",
     "legendFormat": "{{queue}}"
    }
   ]
  },
  {
   "title": "Retry set",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 8, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "max(delayed_job_jobs_errored_total{space=\"$SpaceName\"})",
     "legendFormat": "{{queue}}"
    }
   ]
  },
  {
   "title": "CPU by app ",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 0 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "expr": "avg(cpu{space=\"$SpaceName\" , app=~\"$Apps\" }) by (app)",
     "legendFormat": "{{app}}"
    }
   ]
  },
  {
   "title": "Jobs processed every second",
   "type": "timeseries",
   "gridPos": { "h": 15, "w": 12, "x": 0, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "ops" } },
   "targets": [
    {
     "expr": "sum(rate(delayed_job_job_runtime_seconds_count{space=\"$SpaceName\"}[1m]))",
     "legendFormat": "Successful jobs"
    },
    {
     "expr": "sum(rate(delayed_job_jobs_failed_total{space=\"$SpaceName\"}[1m]))",
     "legendFormat": "Failed jobs"
    }
   ]
  },
  {
   "title": "Memory by app ",
   "type": "graph",
   "gridPos": { "h": 10, "w": 12, "x": 12, "y": 9 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "expr": "avg(memory_utilization{space=\"$SpaceName\" , app=~\"$Apps\" }) by (app)",
     "legendFormat": "{{app}}"
    }
   ]
  },
  {
   "title": "Jobs processed by queue",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 19 },
   "yaxes": [
    { "format": "ops" }
   ],
   "targets": [
    {
     "expr": "sum(rate(delayed_job_job_runtime_seconds_count{space=\"$SpaceName\"}[1m])) by (queue)",
     "legendFormat": "Processed in {{queue}}"
    },
    {
     "expr": "sum(rate(delayed_jobs_jobs_failed_total{space=\"$SpaceName\"}[1m])) by (queue)",
     "legendFormat": "Failed in {{queue}}"
    }
   ]
  },
  {
   "title": "Jobs processed by job type",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 19 },
   "yaxes": [
    { "format": "ops" }
   ],
   "targets": [
    {
     "expr": "sum(rate(delayed_job_job_runtime_seconds_count{space=\"$SpaceName\"}[1m])) by (instance)",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Jobs enqueued",
   "type": "graph",
   "description": "Sidekiq Jobs Enqueued per minute",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 26 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(rate(delayed_job_jobs_enqueued_total{space=\"$SpaceName\"}[1m])) by (queue, instance) * 60",
     "legendFormat": "{{queue}}-{{instance}}"
    }
   ]
  },
  {
   "title": "Jobs enqueued",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 26 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(rate(delayed_job_jobs_enqueued_total{space=\"$SpaceName\"}[1m])) by (queue)",
     "legendFormat": "{{queue}}"
    }
   ]
  },
  {
   "title": "Job processing average time percentiles",
   "type": "graph",
   "gridPos": { "h": 9, "w": 7, "x": 0, "y": 34 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "histogram_quantile(0.99, sum(rate(delayed_job_job_runtime_seconds_bucket{space=\"$SpaceName\"}[1m])) by (le)) ",
     "legendFormat": "99th percentile"
    },
    {
     "expr": "histogram_quantile(0.5, sum(rate(delayed_job_job_runtime_seconds_bucket{space=\"$SpaceName\"}[1m])) by (le)) ",
     "legendFormat": "50th percentile"
    }
   ]
  },
  {
   "title": "Job processing average time by job",
   "type": "graph",
   "gridPos": { "h": 9, "w": 17, "x": 7, "y": 34 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "max(rate(delayed_job_job_runtime_seconds_sum[1m])) by (instance)/max(rate(delayed_job_job_runtime_seconds_count[1m])) by (instance) ",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Job Runtime Bar Gauge",
   "type": "bargauge",
   "gridPos": { "h": 6, "w": 24, "x": 0, "y": 43 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "delta" ] } },
   "targets": [
    {
     "expr": "sum(delayed_job_job_runtime_seconds_bucket) by (le)",
     "legendFormat": "{{le}}"
    }
   ]
  }
 ]
}