{
 "title": "Yabeda Sidekiq",
 "time": { "from": "now-15m", "to": "now" },
 "refresh": "10s",
 "templating": {
  "list": [
   {
    "name": "SpaceName",
    "label": "SpaceName",
    "query": {
     "query": "label_values(sidekiq_active_workers_count,space)"
    }
   },
   {
    "name": "Apps",
    "label": "Apps",
    "query": {
     "query": "label_values(sidekiq_active_workers_count,app)"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "Jobs waiting",
   "type": "stat",
   "description": "Number of jobs waiting in queues to be executed",
   "gridPos": { "h": 4, "w": 4, "x": 0, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "max(sidekiq_jobs_waiting_count{space=\"$SpaceName\"})",
     "legendFormat": "{{queue}}"
    }
   ]
  },
  {
   "title": "Jobs latency",
   "type": "stat",
   "description": "Queue latency is the difference in seconds since the oldest job in the queue was enqueued. Or how long job is waiting its turn to be executed.",
   "gridPos": { "h": 4, "w": 4, "x": 4, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "max(sidekiq_queue_latency{space=\"$SpaceName\"})",
     "legendFormat": "{{queue}}"
    }
   ]
  },
  {
   "title": "Retry set",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 8, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "max(sidekiq_jobs_retry_count{space=\"$SpaceName\"})",
     "legendFormat": "{{queue}}"
    }
   ]
  },
  {
   "title": "CPU by app ",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 0 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "expr": "avg(cpu{space=\"$SpaceName\" , app=~\"$Apps\" }) by (app)",
     "legendFormat": "{{app}}"
    }
   ]
  },
  {
   "title": "Sidekiq PaaS instances",
   "type": "stat",
   "gridPos": { "h": 5, "w": 6, "x": 0, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "count by (app) (sidekiq_active_processes{space=\"$SpaceName\" , app=~\"$Apps\" })",
     "legendFormat": "{{app}}"
    }
   ]
  },
  {
   "title": "Active threads",
   "type": "stat",
   "gridPos": { "h": 5, "w": 6, "x": 6, "y": 4 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(sidekiq_active_workers_count{space=~\"$SpaceName\", app=~\"$Apps\"}) by (app)",
     "legendFormat": "{{app}}"
    }
   ]
  },
  {
   "title": "Sidekiq Active Threads (Cluster Wide)",
   "type": "graph",
   "gridPos": { "h": 10, "w": 12, "x": 0, "y": 9 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(sidekiq_active_workers_count{space=\"$SpaceName\", app=~\"$Apps\"}) by(app)",
     "legendFormat": "{{app}}"
    }
   ]
  },
  {
   "title": "Memory by app ",
   "type": "graph",
   "gridPos": { "h": 10, "w": 12, "x": 12, "y": 9 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "expr": "avg(memory_utilization{space=\"$SpaceName\" , app=~\"$Apps\" }) by (app)",
     "legendFormat": "{{app}}"
    }
   ]
  },
  {
   "title": "Jobs processed every second",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 24, "x": 0, "y": 19 },
   "fieldConfig": { "defaults": { "unit": "ops" } },
   "targets": [
    {
     "expr": "sum(rate(sidekiq_jobs_success_total{space=\"$SpaceName\"}[1m]))",
     "legendFormat": "Successful jobs"
    },
    {
     "expr": "sum(rate(sidekiq_jobs_failed_total{space=\"$SpaceName\"}[1m]))",
     "legendFormat": "Failed jobs"
    }
   ]
  },
  {
   "title": "Jobs processed by queue",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 25 },
   "yaxes": [
    { "format": "ops" }
   ],
   "targets": [
    {
     "expr": "sum(rate(sidekiq_jobs_success_total{space=\"$SpaceName\"}[1m])) by (queue)",
     "legendFormat": "Processed in {{queue}}"
    },
    {
     "expr": "sum(rate(sidekiq_jobs_failed_total{space=\"$SpaceName\"}[1m])) by (queue)",
     "legendFormat": "Failed in {{queue}}"
    }
   ]
  },
  {
   "title": "Jobs processed by job type",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 25 },
   "yaxes": [
    { "format": "ops" }
   ],
   "targets": [
    {
     "expr": "sum(rate(sidekiq_jobs_success_total{space=\"$SpaceName\"}[1m])) by (worker)",
     "legendFormat": "{{worker}}"
    }
   ]
  },
  {
   "title": "Jobs pushed to Sidekiq",
   "type": "graph",
   "description": "Sidekiq Jobs Enqueued per minute",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 32 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(rate(sidekiq_jobs_enqueued_total{space=\"$SpaceName\"}[1m])) by (queue, worker) * 60",
     "legendFormat": "{{queue}}-{{worker}}"
    }
   ]
  },
  {
   "title": "Jobs pushed to Sidekiq by queue",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 32 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(rate(sidekiq_jobs_enqueued_total{space=\"$SpaceName\"}[1m])) by (queue)",
     "legendFormat": "{{queue}}"
    }
   ]
  },
  {
   "title": "Job processing average time percentiles",
   "type": "graph",
   "gridPos": { "h": 9, "w": 7, "x": 0, "y": 40 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "histogram_quantile(0.99, sum(rate(sidekiq_job_runtime_seconds_bucket{space=\"$SpaceName\"}[1m])) by (le)) ",
     "legendFormat": "99th percentile"
    },
    {
     "expr": "histogram_quantile(0.5, sum(rate(sidekiq_job_runtime_seconds_bucket{space=\"$SpaceName\"}[1m])) by (le)) ",
     "legendFormat": "50th percentile"
    }
   ]
  },
  {
   "title": "Job processing average time by job",
   "type": "graph",
   "gridPos": { "h": 9, "w": 17, "x": 7, "y": 40 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "max(rate(sidekiq_job_runtime_seconds_sum[1m])) by (worker)/max(rate(sidekiq_job_runtime_seconds_count[1m])) by (worker) ",
     "legendFormat": "{{ worker }}"
    }
   ]
  },
  {
   "title": "Job Runtime Bar Gauge",
   "type": "bargauge",
   "gridPos": { "h": 6, "w": 24, "x": 0, "y": 49 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "delta" ] } },
   "targets": [
    {
     "expr": "sum(sidekiq_job_runtime_seconds_bucket) by (le)",
     "legendFormat": "{{le}}"
    }
   ]
  }
 ]
}