name: Create Release

on:
  push:
    branches:
      - master

jobs:
  tag_and_release:
    runs-on: ubuntu-20.04
    env:
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

    steps:
      - name: Tag and Create Release
        uses: rymndhng/release-on-push-action@master
        with:
          bump_version_scheme: minor
